version: '3.7'

services:
  ############################
  # publisher service
  ############################
  publisher_app:
    container_name: publisher
    image: webdevops/php-nginx:8.1
    volumes:
      - ./publisher:/var/www
    ports:
      - "8088:80"
      - 3500:3500
    environment:
      WEB_DOCUMENT_ROOT: /var/www/public
    networks:
      - webnet
    depends_on:
      - placement
  ############################
  # consumer service
  ############################
  consumer_app:
    container_name: consumer
    image: webdevops/php-nginx:8.1
    volumes:
      - ./consumer:/var/www
    ports:
      - "8080:80"
      - 3501:3500
    environment:
      WEB_DOCUMENT_ROOT: /var/www/public
      DB_HOST: db
      DB_DATABASE: input_service
      DB_USERNAME: user
      DB_PASSWORD: password
    networks:
      - webnet
    depends_on:
      - placement
      - db
  ############################
  # Database
  ############################
  db:
    image: mariadb:latest
    container_name: input_service_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: input_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - input_service_data:/var/lib/mysql
    ports:
      - "3306:3306"
  ############################
  # Dapr sidecar for Publisher app
  ############################
  publisher-dapr:
    container_name: publisher-dapr-sidecar
    image: 'daprio/daprd'
    command:
      [
        './daprd',
        '--app-id',
        'publisher',
        '--app-port',
        '80',
        '--app-protocol',
        'http',
        '--placement-host-address',
        'placement:50006',
        '--components-path',
        '/components',
      ]
    volumes:
      - './publisher/components/:/components'
    depends_on:
      - publisher_app
    network_mode: 'service:publisher_app'
  ############################
  # Dapr sidecar for Consumer app
  ############################
  consumer-dapr:
    container_name: consumer-dapr-sidecar
    image: 'daprio/daprd'
    command:
      [
        './daprd',
        '--app-id',
        'consumer',
        '--app-port',
        '80',
        '--app-protocol',
        'http',
        '--placement-host-address',
        'placement:50006',
        '--components-path',
        '/components',
      ]
    volumes:
      - './consumer/components/:/components'
    depends_on:
      - consumer_app
    network_mode: 'service:consumer_app'
  ############################
  # Dapr
  ############################
  placement:
    container_name: laravel-dapr
    image: 'daprio/dapr'
    command: ['./placement', '-port', '50006']
    ports:
      - 50006:50006
    networks:
      - webnet
  ############################
  # Redis state store
  ############################
  redis:
    container_name: laravel-redis
    image: redis
    ports:
      - 6380:6379
    networks:
      - webnet
networks:
  webnet:
volumes:
  input_service_data:
    driver: local
