apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: otodapr-subscribe
spec:
  topic: orders
  routes:
    rules:
    - match: 'event.type == "create"'
      path: /api/dapr/create
    default: /api/dapr/receive
  pubsubname: otodapr-pubsub-topics
